const DEFAULTS = { enabled: true, challengeType: 'countdown', waitDuration: 30, bypassDuration: 10 };
const PRESETS = { weekday: [{ startTime: '09:00', endTime: '17:00', days: ['Mon','Tue','Wed','Thu','Fri'] }], evening: [{ startTime: '17:00', endTime: '21:00', days: ['Mon','Tue','Wed','Thu','Fri'] }], daily: [{ startTime: '09:00', endTime: '17:00', days: WaitAMinuteRules.DAYS }] };
let state = { settings: DEFAULTS, rules: [] }; let editing = null; let confirmation = null;
const $ = (id) => document.getElementById(id);
document.addEventListener('DOMContentLoaded', init);
async function init() { await load(); bind(); render(); }
async function load() { const data = await chrome.storage.sync.get(['settings','rules']); state.settings = { ...DEFAULTS, ...(data.settings || {}) }; state.rules = WaitAMinuteRules.validateRules(data.rules) || []; }
function bind() {
  $('acknowledge').onclick = async () => { await chrome.storage.local.set({ onboardingAcknowledged: true }); render(); };
  $('addButton').onclick = addRule; $('domainInput').onkeydown = (e) => { if (e.key === 'Enter') addRule(); };
  $('domainList').onclick = (e) => { const domain = e.target.dataset.domain; if (e.target.matches('[data-edit]')) openRule(domain); if (e.target.matches('[data-remove]')) confirm(`Remove ${domain}?`, 'This will stop blocking the domain.', () => removeRule(domain)); };
  $('enableToggle').onchange = () => saveSettings({ enabled: $('enableToggle').checked });
  $('challengeType').onchange = () => saveSettings({ challengeType: $('challengeType').value });
  $('waitDuration').onchange = () => saveSettings({ waitDuration: Number($('waitDuration').value) }); $('bypassDuration').onchange = () => saveSettings({ bypassDuration: Number($('bypassDuration').value) });
  document.querySelectorAll('.tab').forEach((tab) => tab.onclick = () => selectTab(tab.dataset.tab));
  $('scheduleMode').onchange = renderSchedule; $('addTimeSlot').onclick = () => { editing.timeSlots.push(defaultSlot()); renderSchedule(); };
  $('saveRule').onclick = saveRule; $('exportConfig').onclick = exportConfig; $('importConfig').onchange = importConfig;
  $('resetStatistics').onclick = () => confirm('Reset statistics?', 'This permanently deletes local statistics only.', resetStatistics);
  $('confirmAction').onclick = () => confirmation?.();
}
async function render() { const local = await chrome.storage.local.get('onboardingAcknowledged'); $('onboarding').hidden = Boolean(local.onboardingAcknowledged); $('app').hidden = !local.onboardingAcknowledged; $('enableToggle').checked = state.settings.enabled; $('challengeType').value = state.settings.challengeType; $('waitDuration').value = state.settings.waitDuration; $('bypassDuration').value = state.settings.bypassDuration; $('waitDurationSection').hidden = state.settings.challengeType !== 'countdown'; renderRules(); renderStats(); }
function renderRules() { $('domainList').innerHTML = state.rules.length ? state.rules.map((rule) => `<article class="rule"><div><strong>${escapeHtml(rule.domain)}</strong><p>${rule.blockType === 'hard' ? 'Hard block' : 'Soft block'} · ${scheduleText(rule)}</p></div><div><button data-edit data-domain="${escapeHtml(rule.domain)}">Edit</button><button data-remove data-domain="${escapeHtml(rule.domain)}" aria-label="Remove ${escapeHtml(rule.domain)}">Remove</button></div></article>`).join('') : '<p class="empty">No blocked domains yet.</p>'; }
function escapeHtml(value) { const span = document.createElement('span'); span.textContent = value; return span.innerHTML; }
function scheduleText(rule) { if (!rule.timeSlots.length) return 'All day'; const s = rule.timeSlots[0]; if (rule.timeSlots.length > 1) return `${rule.timeSlots.length} schedules`; return `${formatTime(s.startTime)}–${formatTime(s.endTime)} · ${s.days.length === 7 ? 'Daily' : s.days.join(', ')}`; }
function formatTime(time) { return new Date(`2000-01-01T${time}:00`).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }); }
async function addRule() { const domain = WaitAMinuteRules.normaliseHostname($('domainInput').value); if (!WaitAMinuteRules.validateRules([{ domain, blockType: 'soft', timeSlots: [] }])) return status('Enter a valid domain, such as example.com.', true); if (state.rules.some((rule) => rule.domain === domain)) return status('That domain is already blocked.', true); state.rules.push({ domain, blockType: 'soft', timeSlots: [] }); $('domainInput').value = ''; openRule(domain); }
function openRule(domain) { editing = structuredClone(state.rules.find((rule) => rule.domain === domain)); $('modalDomain').textContent = editing.domain; document.querySelector(`input[name="blockType"][value="${editing.blockType}"]`).checked = true; $('scheduleMode').value = presetName(editing.timeSlots); renderSchedule(); $('ruleDialog').showModal(); }
function presetName(slots) { for (const [name, preset] of Object.entries(PRESETS)) if (JSON.stringify(slots) === JSON.stringify(preset)) return name; return slots.length ? 'custom' : 'all-day'; }
function defaultSlot() { return { startTime: '09:00', endTime: '17:00', days: ['Mon','Tue','Wed','Thu','Fri'] }; }
function renderSchedule() { const mode = $('scheduleMode').value; $('customSchedule').hidden = mode !== 'custom'; if (mode in PRESETS) editing.timeSlots = structuredClone(PRESETS[mode]); if (mode === 'all-day') editing.timeSlots = []; if (mode !== 'custom') return; $('timeSlotList').innerHTML = editing.timeSlots.map((slot, index) => `<div class="slot"><input data-time="start" data-index="${index}" type="time" value="${slot.startTime}"><span>to</span><input data-time="end" data-index="${index}" type="time" value="${slot.endTime}"><button type="button" data-slot-remove="${index}">Remove</button><div class="days">${WaitAMinuteRules.DAYS.map((day) => `<label><input data-day="${day}" data-index="${index}" type="checkbox" ${slot.days.includes(day) ? 'checked' : ''}>${day}</label>`).join('')}</div></div>`).join(''); $('timeSlotList').onclick = (event) => { const index = Number(event.target.dataset.slotRemove); if (Number.isInteger(index)) { editing.timeSlots.splice(index,1); renderSchedule(); } }; $('timeSlotList').onchange = (event) => { const index = Number(event.target.dataset.index); if (event.target.dataset.time) editing.timeSlots[index][event.target.dataset.time === 'start' ? 'startTime' : 'endTime'] = event.target.value; if (event.target.dataset.day) { const days = editing.timeSlots[index].days; const day = event.target.dataset.day; event.target.checked ? days.push(day) : editing.timeSlots[index].days = days.filter((item) => item !== day); } }; }
async function saveRule(event) { event.preventDefault(); editing.blockType = document.querySelector('input[name="blockType"]:checked').value; if ($('scheduleMode').value === 'custom') renderSchedule(); if (!WaitAMinuteRules.validateRules([editing])) return status('Each custom slot needs different times and at least one day.', true); const index = state.rules.findIndex((rule) => rule.domain === editing.domain); if (index < 0) state.rules.push(editing); else state.rules[index] = editing; await saveRules(); $('ruleDialog').close(); status('Rule saved.'); }
async function removeRule(domain) { state.rules = state.rules.filter((rule) => rule.domain !== domain); await saveRules(); status('Rule removed.'); }
async function saveRules() { await chrome.storage.sync.set({ rules: state.rules }); renderRules(); }
async function saveSettings(change) { state.settings = { ...state.settings, ...change }; await chrome.storage.sync.set({ settings: state.settings }); await render(); }
function selectTab(name) { document.querySelectorAll('.tab').forEach((tab) => { const active = tab.dataset.tab === name; tab.classList.toggle('active',active); tab.setAttribute('aria-selected',active); }); document.querySelectorAll('.panel').forEach((panel) => panel.classList.toggle('active',panel.id === `${name}-tab`)); }
function confirm(title, text, action) { confirmation = action; $('confirmTitle').textContent = title; $('confirmText').textContent = text; $('confirmDialog').showModal(); }
async function resetStatistics() { await chrome.runtime.sendMessage({ action: 'resetStatistics' }); await renderStats(); status('Statistics reset.'); }
async function exportConfig() { const payload = { format: 'waitaminute-config', version: 1, settings: state.settings, rules: state.rules }; const url = URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)], { type:'application/json' })); const link = Object.assign(document.createElement('a'), { href:url, download:'waitaminute-settings.json' }); link.click(); URL.revokeObjectURL(url); status('Settings exported.'); }
async function importConfig(event) { const file = event.target.files[0]; event.target.value = ''; if (!file) return; try { const config = JSON.parse(await file.text()); const rules = config.format === 'waitaminute-config' && config.version === 1 && WaitAMinuteRules.validateRules(config.rules); if (!rules || !config.settings) throw new Error(); const settings = { ...DEFAULTS, ...config.settings }; confirm('Replace configuration?', `Import ${rules.length} domain rule${rules.length === 1 ? '' : 's'} and replace your current settings.`, async () => { state = { settings, rules }; await chrome.storage.sync.set({ settings, rules }); await render(); status('Configuration imported.'); }); } catch (_) { status('That is not a valid WaitAMinute settings file.', true); } }
async function renderStats() { const stats = await chrome.runtime.sendMessage({ action:'getStatistics' }); const today = WaitAMinuteRules.localDateKey(); const current = stats.dailyStats?.[today] || { blockedAttempts:0,challengesCompleted:0 }; $('todayBlocked').textContent = current.blockedAttempts; $('todayCompleted').textContent = current.challengesCompleted; $('successRate').textContent = current.blockedAttempts ? `${Math.max(0,Math.round((current.blockedAttempts-current.challengesCompleted)/current.blockedAttempts*100))}%` : '0%'; const dates = Array.from({length:14},(_,i) => WaitAMinuteRules.localDateKey(new Date(Date.now()-(13-i)*86400000))); const max = Math.max(1,...dates.map((date) => stats.dailyStats?.[date]?.blockedAttempts || 0)); $('chartContainer').innerHTML = dates.map((date) => `<div title="${date}: ${stats.dailyStats?.[date]?.blockedAttempts || 0} blocks" style="height:${(stats.dailyStats?.[date]?.blockedAttempts || 0)/max*100}%"></div>`).join(''); const totals = {}; Object.values(stats.dailyStats || {}).forEach((day) => Object.entries(day.domains || {}).forEach(([domain, value]) => { totals[domain] = (totals[domain]||0)+value.attempts; })); $('domainStatsList').innerHTML = Object.entries(totals).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([domain,count])=>`<p>${escapeHtml(domain)} <strong>${count}</strong></p>`).join('') || '<p class="empty">No statistics yet.</p>'; }
function status(message, error=false) { $('statusMessage').textContent = message; $('statusMessage').classList.toggle('error',error); }
